### PR TITLE
Feature/35088 - Logo

### PR DESCRIPTION
**Pull request by kjugi**
+ Simplify logo styles
+ Add new logo as svg file
+ Delete old logo

https://dev.snowdog.pro/issues/35088

### CODE REVIEW

**Comment by Igloczek** [comment]
@szafran89 let's check this solution and merge if it fits or reject if not.
Sorry for duplicating your work 😢

**Comment by Januszpl** [comment]
And I have this for CR in redmine...

**Comment by Igloczek** [comment]
@Januszpl changed
@kjugi remembert to always add links to redmine

**Comment by szafran89** [comment]
I think we can close this PR, I have similar changes on my branch.

**Pull request closed without merging**
