### PR TITLE
Feature/34777

### PR DESCRIPTION
**Pull request by anqaka**
radio input a11y features
issue #125

### CODE REVIEW

**Comment by Januszpl** [comment]
I would put fieldset and legend here. It should be in some other wrapper that use basic radio element. Sth like it is in magento-ui

**Comment by anqaka** [comment]
IMO we can do smth like fieldset component or implement it into module, I would like to set those a11y feature to be clear for everyone that this is the way we should build radio inputs - with fieldset and legend

**Comment by Januszpl** [comment]
I will put this changes in my PR as well with fixed variables names

**Comment by anqaka** [comment]
I think we can close this PR, it's already implemented.

**Pull request closed without merging**
